In [7]:
import numpy as np

In [8]:
numbers = np.array([5,10,15,20,25])
print(numbers)
print(numbers.dtype)

[ 5 10 15 20 25]
int64


In [9]:
numbers[numbers<20]

array([ 5, 10, 15])

In [10]:
numbers_float = np.array([5.5,10.8,10.2,15.8,20.9])
print(numbers_float)
print(numbers_float.dtype)

[ 5.5 10.8 10.2 15.8 20.9]
float64


In [11]:
letter = np.array(['a','b','c','d'])
print(letter)
print(letter.dtype)

['a' 'b' 'c' 'd']
<U1


In [12]:
numbers = np.array([5,10,15,20,25])
print(numbers + 5)

[10 15 20 25 30]


In [13]:
print(numbers * 5)

[ 25  50  75 100 125]


In [14]:
print(numbers ** 5)

[   3125  100000  759375 3200000 9765625]


In [15]:
numbers[0]

np.int64(5)

In [16]:
numbers[-3]

np.int64(15)

In [17]:
numbers[:3]

array([ 5, 10, 15])

In [18]:
numbers[-1:]

array([25])

In [19]:
matrix= np.array([[10,20,30],[40,50,60],[70,80,90]])
matrix[:3]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [20]:
numbers1 = np.array([10,20,30,40,50])
print(np.mean(numbers1),
np.median(numbers1),
np.min(numbers1),
np.max(numbers1),
np.sum(numbers1))

30.0 30.0 10 50 150


In [21]:
print(np.std(numbers1))

14.142135623730951


In [22]:
print(np.var(numbers1))

200.0


In [23]:
#  array operations
print(np.sort(numbers1)) #--> sorts the values in ascending order
print(np.unique(numbers1)) #--> it removes duplicates and return the unique values
print(np.argmax(numbers1)) # --> it gives the position of the maximum value
print(np.argmin(numbers1))# --> gives the position of minimum value

[10 20 30 40 50]
[10 20 30 40 50]
4
0


In [24]:
print(numbers1 >=22) #-->this is called boolen filtering where we get True / False as output

[False False  True  True  True]


In [25]:
num = np.array([1,2,3,4,5,6])
martrix= num.reshape(3,2)# --> converts 1D array in to multi dimentional array
print(martrix)


[[1 2]
 [3 4]
 [5 6]]


In [26]:
flat = martrix.flatten() #--> to make multi dimentional array in to 1D array
print(flat)

[1 2 3 4 5 6]


In [27]:
martrix.ravel() #--> same as flatten but it won't save as copy but return a view of the organized data

array([1, 2, 3, 4, 5, 6])

In [28]:
mis_num = np.array([10,20,np.nan,40,np.nan,50])
print(mis_num)

[10. 20. nan 40. nan 50.]


In [29]:
mis_num[~np.isnan(mis_num)] #--> to get non_missing values we can use boolen mask

array([10., 20., 40., 50.])

In [30]:
# to calculate sum, mean, median , std, var while ignoring missing values we use nansum, nanmean, nanmedian, nanstd, nanvar

print(np.nansum(mis_num))
print(np.nanmean(mis_num))
print(np.nanmedian(mis_num))
print(np.nanstd(mis_num))
print(np.nanvar(mis_num))


120.0
30.0
30.0
15.811388300841896
250.0


In [31]:
#  To generate random integers
ran_num=np.random.randint(1,10,size=5)
print(ran_num)
#  to get random float values
ran_float = np.random.rand()
print(ran_float)
#  To get same random numbers everytime we use seed
np.random.seed(16)
same_ran = np.random.randint(1,10,size=7)
print(same_ran)

[3 4 3 8 4]
0.0508732774302697
[6 2 5 5 1 1 9]


# Numpy Exercise

In [32]:
# Create 1D array of integers from 0 to 9
num=np.array([0,1,2,3,4,5,6,7,8,9])

In [33]:
# Create a 3x3 array of all zeros, then a 3x3 array of all ones
print(np.zeros((3,3)))
print(np.ones((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
# Creat a 5x5 identity matrix.
_5x5_identity_matrix = np.identity((5))
_5x5_identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
#Create an array of 10 evenly spaced numbersbetween 0 and 1
_10esn= np.arange(0,1,0.1)
_10esn
#or
ten_ESN= np.linspace(0,1,10)
ten_ESN

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [36]:
#Create a 4x4 array filled with random integers between 1 and 100
np.random.randint(1,100, size =(4,4))

array([[59, 19, 33, 66],
       [32, 75, 35, 79],
       [94, 78,  1, 29],
       [29, 60,  9, 99]])

In [37]:
# From a 1D array of 20 elements and extract every 3rd element
np.random.seed(16)
a=np.random.randint(1,100,20)
print(a[::3])


[42 69 42 31 33 75 94]


In [38]:
np.random.seed(22)
matrix=np.random.randint(1,50, size =(5,5))
matrix

array([[ 5, 45,  1, 37, 39],
       [44, 21,  9, 32, 37],
       [30, 19, 15, 46, 25],
       [30, 40, 35, 42,  9],
       [41,  6, 48, 28, 21]])

In [39]:
#Given 2D array (5x5),extract the middle 3x3 sub-array
np.random.seed(22)
matrix=np.random.randint(1,50, size =(5,5))
matrix
matrix3x3 = matrix[1:4,1:4]
matrix3x3

array([[21,  9, 32],
       [19, 15, 46],
       [40, 35, 42]])

In [40]:
#Reverse a 1D array without using a loop.
num_rev =num[::1]
num_rev

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#Geven a 2D array, extract only the elements graterthan 50( boolean indexing)
np.random.seed(1)
numbers = np.random.randint(40,80,20)
print(numbers)

[77 52 48 49 51 45 55 40 56 41 52 47 46 65 60 77 58 60 51 68]


In [42]:
num_gra_50=numbers[numbers>50]
num_gra_50

array([77, 52, 51, 55, 56, 52, 65, 60, 77, 58, 60, 51, 68])

In [43]:
##Reshaping
# Create a 1D array of12 elements and reshape it into a 3x4 matrix.
_10 = np.array([15,14,11,81,75,64,9,3,44,61,77,22])
mat=_10.reshape(3,4)
mat

array([[15, 14, 11, 81],
       [75, 64,  9,  3],
       [44, 61, 77, 22]])

In [44]:
#Flatten a 2D array back in to 1D array
flattent=mat.flatten()
flattent

array([15, 14, 11, 81, 75, 64,  9,  3, 44, 61, 77, 22])

In [45]:
#Take a 2x3 array and transpose it --verify new shape.
array_1= np.array([1,2,3,4,5,6])
_2x3matrix= array_1.reshape(2,3)
m_transpose=_2x3matrix.transpose()
m_transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
## Boardcasting and operations
#Add a 1D array of shape (3,)to a 2D array pf shape (3,3) and explain what happend
arr_2 = np.array([1,2,3])
arr_2.shape
arr_3 = np.array([1,2,3,4,5,6,7,8,9])
mat_2 = arr_3.reshape(3,3)
mat_2.shape
mat_4=mat_2 + arr_2 # here the 1D array elements are added to 1st row elements od 2D arrey(3x3)
mat_4

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [52]:
# Given an array of tempatures in Celsius,convert all values of fahrenheit in one line (no loop)
#0 celcius = 32 fahrenheit 1C = 33.8 --> 1C increase 1.8 F increase+32
temp_C = np.array([33,35,34,32,36,38,37,39,40])
temp_F = temp_C*1.8+32
temp_F

array([ 91.4,  95. ,  93.2,  89.6,  96.8, 100.4,  98.6, 102.2, 104. ])

In [53]:
arr_4 = np.array([3,2,1,6,5,4,9,8,7])
mat_3=arr_4.reshape(3,3)
mat_3


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [56]:
#Create two arrays of the same shape and compute their element-wise sum,differenc and product
#Addition
Add_2_arr = mat_3 + mat_4
Add_2_arr


array([[ 5,  6,  7],
       [11, 12, 13],
       [17, 18, 19]])

In [57]:
#Difference
Sub_2_arr = mat_3 - mat_4
Sub_2_arr

array([[ 1, -2, -5],
       [ 1, -2, -5],
       [ 1, -2, -5]])

In [58]:
#Product
Mul_2_arr = mat_3 * mat_4
Mul_2_arr

array([[ 6,  8,  6],
       [30, 35, 36],
       [72, 80, 84]])